### ISSUE TITLE
Popup events detection

### ISSUE THREAD

**Issue by dabajabaza** [justinmanley/leaflet-draw-toolbar#1]
Hi @justinmanley . Thanks for your wonderful leaflet plugin. But is there a way to detect which action was executed in popup and return a shape object?  I described the problem [here](https://gis.stackexchange.com/questions/259250/how-to-detect-delete-or-edit-events-in-popup-menu-created-with-leaflet-draw) in more detail.

**Comment by justinmanley** [comment]
Thanks for reporting this behavior. This is a bug. I have a fix, will hopefully submit it tomorrow and do a new release. Once that's done, you'll be able to listen to 'draw:edited' and 'draw:deleted' events from the popup edit toolbar as well as the control edit toolbar.

**Comment by justinmanley** [comment]
Please give this a try and let me know if it fixes your issue. Once you confirm that the issue is fixed I will do a new patch release.

**Comment by dabajabaza** [comment]
@justinmanley I checked it and it works fine. But I noticed that the returned objects for draw:created and draw:edited or deleted events are different. Is this ok?

![image](https://user-images.githubusercontent.com/11490311/31992902-4a83d378-b984-11e7-97a8-364be69498e4.png)

Will you answer me on  [gis.stackexchange.com](https://gis.stackexchange.com/questions/259250/how-to-detect-delete-or-edit-events-in-popup-menu-created-with-leaflet-draw)  or should I delete my question?

**Comment by justinmanley** [comment]
Great! Glad it works now. I've created a release with this bugfix.

Yes, it is expected that draw:created and draw:edited / draw:deleted should have different events; see the Leaflet.draw documentation: https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html.
