### ISSUE TITLE
LeafletToolbar  Incompatibility with new version of Leaflet.toolbar

### ISSUE THREAD

**Issue by veragreen119** [justinmanley/leaflet-draw-toolbar#15]
I am setting up a new implementation and I ran into a few erros which need a quick find/replace:
Error:
- LeafletToolbar is not defined

Using the following plugins:
- [Leaflet.toolbar](https://github.com/Leaflet/Leaflet.toolbar) from master
- [leaflet-draw-toolbar](https://github.com/justinmanley/leaflet-draw-toolbar/tree/gh-pages)
- [Leaflet.draw 0.3.1](https://github.com/Leaflet/Leaflet.draw/tree/0.3.1)

### MODIFICATIONS:
- **leaflet.draw-toolbar.js** was UPDATED to work with the current version of Leaflet.toolbar
  - replaced LeafletToolbar with L.Toolbar2
  - replaced L.Toolbar2.toolbarAction with L.Toolbar2.Action

**Comment by syonfox** [comment]
note you want a newer version of leaflet.draw then 0.3.1 jake uses 0.4.12
