### ISSUE TITLE
Uncaught ReferenceError: map is not defined ColorPicker.js:34

### ISSUE THREAD

**Issue by t1a2l** [justinmanley/leaflet-draw-toolbar#3]

**Comment by t1a2l** [comment]
@justinmanley

**Comment by t1a2l** [comment]
I get this error when trying your popup example code using color picker js. after choosing a color the I can't click the color picker again it is stuck and then on the chrome developer tools I get this error.

**Comment by justinmanley** [comment]
Hi, Tal. Thanks for opening an issue!

The popup.html example still works fine for me. More details will help me understand the problem that you're having.

Can you provide the error message that you see in Chrome developer tools?
What operating system / Chrome version are you using?
What code are you trying to run? (Are you trying to run examples/popup.html?) How are you running it?
Did you clone this repository, or install it via npm?

**Comment by t1a2l** [comment]
Hi, 
The error: Uncaught ReferenceError: map is not defined ColorPicker.js:34
Win10 64bit, Chrome 64bit version 63.0.3239.132
I am runing the code of the popup.html in the example as part of my code: I am using google gecode to get cords by location, once i get the ok from google, I ran the script part of the popup.html code.
When drawing a circle, after pressing the circle I get the popup, I change the color and the popup get stuck. (Uncaught ReferenceError: map is not defined ColorPicker.js:34) somthing to do with map is not defined in one of the functions in the color picker js. I can still draw other shapes.
I Installed via npm.

**Comment by justinmanley** [comment]
Thanks for noticing this. The issue was one of scope; ColorPicker was only intended to be used in popup.html, so the reference to 'map' in _createIcon was actually resolving to the 'map' defined in popup.html.

Fixed in https://github.com/justinmanley/leaflet-draw-toolbar/commit/e3371746f0e6fade35624e3e5801933f23604dcb by keeping a reference to 'map' in the ColorPicker class.

**Comment by t1a2l** [comment]
Thank you for your help.
