### ISSUE TITLE
Close Popup-Toolbar when clicking outside of the Layer

### ISSUE THREAD

**Issue by SiegmannGiS** [justinmanley/leaflet-draw-toolbar#5]
Is there a way of closing the popup toolbar when clicking outside of the layer?
When the Popup bar once is opened there is no possiblity of closing it. 
This would be a nice feature!

**Comment by emranch31** [comment]
I need to have the solution for this as well

**Comment by justinmanley** [comment]
One way that you can implement this without modifying the library is by adding a 'close popup' action inside your popup (e.g. an 'X').

If you specifically want the behavior of tapping on the map to close the popup (without opening another popup), you should be able to implement this in application code as well by adding custom tap handlers to the map when the popup is added (and adding code to the onRemove method of the popup toolbar to clean up those handlers once the popup closes).

See also the (admittedly meager) documentation on building custom toolbars: https://github.com/Leaflet/Leaflet.toolbar/wiki/Building-custom-toolbars.

If you get this working in your code, I'd be happy to review a PR to upstream the functionality.
